seqLength=4
delayRes=1.0
traceCount=1
traceFile=james_ams_recv2.csv
bestPredCount=10
tmin=1
tmax=13
learnMode=0
strict=0
objective=1
useOverlap=1
depth=6

start 2

nxt 2 1
plen 3 1
icmpv6_type 4 1
l4 5 1
iat 6 1
hlim 7 1
flow 8 1

begin

nxt==0
nxt==43
nxt==44
nxt==50
nxt==51
nxt==60

plen<=64
plen>=128
plen>=512
plen>=1280

hlim<=16
hlim>=200

flow==0

end

HAS_HBH_EH  = (1)
HAS_RT_EH   = (2)
HAS_FRAG_EH = (3)
HAS_ESP_EH  = (4)
HAS_AH_EH   = (5)
HAS_DST_EH  = (6)
PLEN_SMALL  = (7)
PLEN_MED    = (8)
PLEN_BIG    = (9)
PLEN_HUGE   = (10)
HLIM_LOW    = (11)
HLIM_HIGH   = (12)
FLOW_ZERO   = (13)

targets
begin
(3)
end
